### ISSUE TITLE
Please implement marker clustering

### ISSUE THREAD

**Issue by lukehutch** [firebase/geofire#3]
GeoFire is great, but would be even more useful with marker clustering:

https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-markercluster/

Would this be able to be ported to GeoFire?

https://github.com/Leaflet/Leaflet.markercluster

**Comment by jdimond** [comment]
Mapbox's clustering already use latitude/longitude pairs to provide this feature. Since there is no straightforward solution to make this more efficient with GeoFire I would advise to just let Mapbox handle this by adding the latitude/longitude pairs you receive in the GeoFire callbacks. The combination of both libraries will be more powerful than letting GeoFire just reimplement this feature.
