### ISSUE TITLE
time based geoqueries

### ISSUE THREAD

**Issue by victusfate** [firebase/geofire#5]
I've got a dataset with lat lon and time, and I'd like to be able to do geoqueries within a window of time.

What do you suggest would be a good approach to take here?

Ideally I could have a query system something like (lat,lon,radius,tstart,tend) 

current idea is for a fixed window (say last 30min) manually removing keys with a t value > 30min but this won't work for different times

**Comment by jwngr** [comment]
This is not possible because the underlying Firebase SDK only allows for querying against a single thing at a time. In the case of GeoFire, we need to query against the geohash. There are some pretty unpleasant ways to achieve this, but you have to manage it yourself and it is not very efficient. See https://github.com/firebase/geofire-java/issues/37 and https://github.com/firebase/geofire-js/issues/59#issuecomment-70350560 for some more details.
